added PSAT client
Skatteetaten/kubernetes-reactor-coroutines-client pull request #30
Opened 2021-05-19 11:38 UTC by jarlehansen

2021-05-19 11:38 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/kubernetes/KubernetesClientExtentions.kt
> +    override fun token(audience: String?): String? {
Denne verdien bør kanskje caches?

2021-05-20 06:19 UTC, mikand13 requested changes
Generelt er jeg ikke særlig fan av "mange klasser i en fil"-trenden i kotlin. Er det noe vi bør diskutere eller skal jeg bare bøye av der?

2021-05-20 06:19 UTC, mikand13 commented on src/main/kotlin/no/skatteetaten/aurora/kubernetes/KubernetesClientExtentions.kt
> +    override fun token(audience: String?): String? {
Ja, det er en one-time IO? Load den som en bean?

2021-05-20 06:19 UTC, mikand13 commented on src/main/kotlin/no/skatteetaten/aurora/kubernetes/KubernetesCoroutinesClient.kt
> +        return client.getMany<Kind>(metadata, token, audience).awaitFirstOrNull() ?: emptyList()
Generell kommentar ang. one line returns. Endre de til = metoder?

2021-05-20 07:40 UTC, jarlehansen commented on src/main/kotlin/no/skatteetaten/aurora/kubernetes/KubernetesCoroutinesClient.kt
> +        return client.getMany<Kind>(metadata, token, audience).awaitFirstOrNull() ?: emptyList()
Jeg har ikke i mot å gruppere klasser i en fil, men enig i at det nok er tatt litt langt her. Skal se om jeg kan omorganisere det litt.

2021-05-20 09:08 UTC, mikand13 approved these changes

2021-05-20 11:05 UTC, merged