Feature/aos 7195 springboot275bump
Skatteetaten/kubernetes-reactor-coroutines-client pull request #45
Opened 2022-11-03 13:04 UTC by RuneOfferdal

2022-11-03 13:12 UTC, jarlehansen requested changes

2022-11-03 13:12 UTC, jarlehansen commented on build.gradle.kts
> +tasks.compileJava {
set java versjon i aurora blokka, med denne:
```
versions {
    javaSourceCompatibility = "1.8"
}
```

2022-11-03 13:12 UTC, jarlehansen commented on build.gradle.kts
>      testImplementation("no.skatteetaten.aurora:mockwebserver-extensions-kotlin:1.3.1")
set til version `1.4.0`

2022-11-03 13:15 UTC, RuneOfferdal commented on build.gradle.kts
> +tasks.compileJava {
Will do. Jeg hadde følelsen av at det var en mer elegant måte å gjøre det på enn dette.

2022-11-03 13:17 UTC, RuneOfferdal commented on build.gradle.kts
>      testImplementation("no.skatteetaten.aurora:mockwebserver-extensions-kotlin:1.3.1")
Jepp.

2022-11-03 13:48 UTC, jarlehansen approved these changes

2022-11-04 07:11 UTC, bugge-jorgen approved these changes

2022-11-04 07:18 UTC, merged